### ISSUE TITLE
Libretro GPSP core:

### ISSUE THREAD

**Issue by frthery** [petrockblog/RetroPie-Setup#523]
Hi,

First thanks for all of your work, i have learn a lot with your scripts. I am also following retroarch/libretro project which bring me a lots of informations.
For information, retroarch has integrated a new gba core gpsp (forked from notaz) which is very good and works great.
I suppose it could be interesting if you integrate this new core to retropie.

https://github.com/frthery/ES_RetroPie/blob/master/RetroPie-Setup/scriptmodules/libretrocores/gpsplibretro.sh

Compilation not working on my pi b+ with ES 2.3, but working on my other pi with raspbian.

Compilation error on ES 2.3 :
cc1: out of memory allocating 34588436 bytes after a total of 34848768 bytes
Makefile:297: recipe for target 'gba_memory.o' failed
make: *** [gba_memory.o] Error 1

I suppose a problem of swap ?

Thanks.
